spring:
  application:
    name: task-tracker-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: tracker_user
    password: tracker_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG