server:
  port: 8082

spring:
  application:
    name: task-tracker-scheduler
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  backend-url: "http://localhost:8080/tasks/internal/uncompleted-reports"